export interface Badge {
  title: string;
  href: string;
  img: string;
}

export interface SettingsData {
  siteTitle: string;
  siteDescription: string;
  siteLogo: string;
  siteUrl: string;
  favicon: string;
  icp: string;
  footerText: string;
  siteStartDate: string;
  footerTechInfo: string;
  postsPerPage: string;
  commentProvider: string;
  twikooEnvId: string;
  commentEmojiCdn: string;
  adminEmail: string;
  adminName: string;
  adminPassword: string;
  adminBadge: string;
  mailEnabled: string;
  mailSmtpHost: string;
  mailSmtpPort: string;
  mailSmtpUser: string;
  mailSmtpPass: string;
  mailSmtpSecure: string;
  mailProvider: string;
  mailApiKey: string;
  mailGatewayUrl: string;
  mailGatewayToken: string;
  mailFromEmail: string;
  mailFromName: string;
  mailTemplateReply: string;
  mailTemplateAdmin: string;
  imgbedUrl: string;
  imgbedToken: string;
  fontCssUrl: string;
  fontFamily: string;
  backgroundImage: string;
  heroType: string;
  heroImage: string;
  heroVideo: string;
  linkMarkdown: string;
  showMotto: string;
  mottoTitle: string;
  mottoText: string;
  mottoCtaText: string;
  mottoCtaUrl: string;
  mottoCtaTarget: string;
  footerBadges: string;
}

export const defaultValues: SettingsData = {
  siteTitle: '',
  siteDescription: '',
  siteLogo: '',
  siteUrl: '',
  favicon: '',
  icp: '',
  footerText: '',
  siteStartDate: '',
  footerTechInfo: '',
  postsPerPage: '10',
  commentProvider: 'twikoo',
  twikooEnvId: '',
  commentEmojiCdn: '',
  adminEmail: '',
  adminName: '',
  adminPassword: '',
  adminBadge: '',
  mailEnabled: 'false',
  mailSmtpHost: 'smtp.qq.com',
  mailSmtpPort: '465',
  mailSmtpUser: '',
  mailSmtpPass: '',
  mailSmtpSecure: 'ssl',
  mailProvider: 'none',
  mailApiKey: '',
  mailGatewayUrl: '',
  mailGatewayToken: '',
  mailFromEmail: '',
  mailFromName: '',
  mailTemplateReply: '',
  mailTemplateAdmin: '',
  imgbedUrl: '',
  imgbedToken: '',
  fontCssUrl: '',
  fontFamily: '',
  backgroundImage: '',
  heroType: 'image',
  heroImage: '/hero.webp',
  heroVideo: '',
  linkMarkdown: '',
  showMotto: 'true',
  mottoTitle: '格言',
  mottoText: '',
  mottoCtaText: '',
  mottoCtaUrl: '',
  mottoCtaTarget: '_self',
  footerBadges: '',
};
