// 友链数据
export interface FriendConfigItem {
  name: string;
  url: string;
  description: string;
  avatar: string;
  type: string;
  screenshot: string;
  recommended: boolean;
  sort: number;
}

export const friendsConfig: FriendConfigItem[] = [
  {
    name: "mccsjs",
    url: "https://mccsjs.cn/",
    description: "第一是我自己！！！",
    avatar: "https://mccsjs.cn/img/ico.jpg",
    type: "技术支持",
    screenshot: "https://mccsjs.cn/img/a.jpg",
    recommended: true,
    sort: 1,
  },
  {
    name: "Fomalhaut🥝",
    url: "https://www.fomal.cc/",
    description: "Future is now 🍭🍭🍭",
    avatar: "https://csjs.eu.org/img/fomal.jpg",
    type: "技术支持",
    screenshot: "https://pic.seln.cn/file/picui/xFvnHkOj.jpg",
    recommended: false,
    sort: 2,
  },
  {
    name: "Hexo",
    url: "https://hexo.io/zh-cn/",
    description: "快速、简单且强大的网志框架",
    avatar: "https://d33wubrfki0l68.cloudfront.net/6657ba50e702d84afb32fe846bed54fba1a77add/827ae/logo.svg",
    type: "技术支持",
    screenshot: "",
    recommended: false,
    sort: 3,
  },
  {
    name: "Akilarの糖果屋",
    url: "https://akilar.top/",
    description: "欢迎光临糖果屋",
    avatar: "https://npm.elemecdn.com/akilar-friends@latest/avatar/akilar.top.jpg",
    type: "技术支持",
    screenshot: "https://npm.elemecdn.com/akilar-friends@latest/siteshot/akilar.top.jpg",
    recommended: false,
    sort: 4,
  },
  {
    name: "Astro",
    url: "https://astro.build/",
    description: "为内容驱动的网站打造，速度极快",
    avatar: "https://astro.build/favicon.svg",
    type: "技术支持",
    screenshot: "",
    recommended: false,
    sort: 4.5,
  },
  {
    name: "MmzMing",
    url: "https://tblog.mmzhiku.xyz/",
    description: "哈基米，南北绿豆",
    avatar: "https://i.seln.cn/file/picui/1782119609255_StarDots-2026052116374135506.webp",
    type: "技术支持",
    screenshot: "",
    recommended: false,
    sort: 46,
  },
  {
    name: "Revincx",
    url: "https://blog.revincx.icu/",
    description: "可爱就是正义~",
    avatar: "https://csjs.eu.org/img/r.jpg/",
    type: "一些好朋友~",
    screenshot: "https://csjs.eu.org/img/siteshot.png",
    recommended: false,
    sort: 5,
  },
  {
    name: "梦落の小屋",
    url: "https://blog.dreamfall.cn",
    description: "因为不可能，所以才值得相信",
    avatar: "https://img.mengluo.work/avatar.jpg",
    type: "一些好朋友~",
    screenshot: "https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.dreamfall.cn/",
    recommended: false,
    sort: 6,
  },
  {
    name: "Router",
    url: "https://blog.irislc.net/",
    description: "看上去这路还没走到头",
    avatar: "https://blog.irislc.net/upload/siteImg/siteLogo.webp?v=1758617777942",
    type: "一些好朋友~",
    screenshot: "https://image.thum.io/get/allowJPG/wait/20/width/600/crop/950/https://blog.irislc.net/",
    recommended: false,
    sort: 7,
  },
  {
    name: "Almango",
    url: "https://blog.almango.cn/",
    description: "天真永不消逝，浪漫至死不渝。",
    avatar: "https://blog.almango.cn/favicon.png",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 8,
  },
  {
    name: "Honaisu",
    url: "https://www.denvoshome.xyz/",
    description: "时光流转,岁月更迭",
    avatar: "https://www.denvoshome.xyz/wp-content/uploads/2024/01/blog-icon.jpg",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 9,
  },
  {
    name: "BIIBII",
    url: "https://www.biibii.cn",
    description: "记录生活中的技术脉搏。",
    avatar: "https://www.biibii.cn/usr/uploads/2025/07/3155658037.webp",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 10,
  },
  {
    name: "辰渊尘",
    url: "https://blog.mcxiaochen.top/",
    description: "05后，高中生，内容偏技术向，希望能对你有用QwQ",
    avatar: "https://blog.mcxiaochen.top/favicon.ico",
    type: "一些好朋友~",
    screenshot: "https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/anheyu.com/https://blog.mcxiaochen.top/",
    recommended: false,
    sort: 11,
  },
  {
    name: "裕裕裕的小破宅",
    url: "https://yu-blog.top/",
    description: "一个充满青春活力的技术博客，为初学者提供了优质的博客搭建指南和技术分享。",
    avatar: "https://yu-blog.top/img/avatar.jpg",
    type: "一些好朋友~",
    screenshot: "https://pic.seln.cn/file/siteshot/nOscTmi4.png",
    recommended: true,
    sort: 12,
  },
  {
    name: "s1rius",
    url: "https://s1rius.space/",
    description: "这里有网络安全和其他技术文章",
    avatar: "https://s1rius.space/img/custom/avatar.webp",
    type: "一些好朋友~",
    screenshot: "https://s1rius.space/img/custom/siteshot.webp",
    recommended: false,
    sort: 13,
  },
  {
    name: "ShiroRikkaの小窝",
    url: "https://blog.shirorikka.dpdns.org/",
    description: "邪王真眼是最强的！",
    avatar: "http://q.qlogo.cn/headimg_dl?dst_uin=2985772684&spec=640&img_type=jpg",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 14,
  },
  {
    name: "旧絮",
    url: "https://blog.zhkax.cn/",
    description: "心向往之行必能至",
    avatar: "https://thirdqq.qlogo.cn/g?b=qq&nk=3362991369&s=640",
    type: "一些好朋友~",
    screenshot: "https://csjs.eu.org/img/jx.png/",
    recommended: false,
    sort: 15,
  },
  {
    name: "博客录",
    url: "https://boke.lu",
    description: "boke.lu · 博客收录展示平台~",
    avatar: "https://boke.lu/logo/透明底圆底.png",
    type: "一些好朋友~",
    screenshot: "https://csjs.eu.org/img/bkl.png/",
    recommended: false,
    sort: 16,
  },
  {
    name: "THW’s Blog",
    url: "https://tianhw.top",
    description: "前途似海，来日方长",
    avatar: "https://image.tianhw.top/avatar.webp",
    type: "一些好朋友~",
    screenshot: "https://i.seln.cn/file/picui/1787292940944__EC748273-52B8-4129-BE0F-089BCF0C57A3_.webp",
    recommended: false,
    sort: 17,
  },
  {
    name: "ZLA 小站",
    url: "https://zla.pub/",
    description: "月亮不抱你，星星会落在你怀里✨🌙",
    avatar: "https://zla.pub/_next/image?url=%2Fimages%2Favatar.jpg&w=384&q=75",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 18,
  },
  {
    name: "葱苓小筑",
    url: "https://blog.ciraos.top",
    description: "风带来了故事的种子，时间使其发芽。",
    avatar: "https://files.seeusercontent.com/2026/02/28/Vxb1/avatar2.avif",
    type: "一些好朋友~",
    screenshot: "https://files.seeusercontent.com/2026/02/28/D9gw/siteshot.avif",
    recommended: false,
    sort: 19,
  },
  {
    name: "益友网站",
    url: "https://www.yiyou.bj.cn",
    description: "美好的日常生活值得我们去记录，希望我们的生活每天都能充满着乐趣跟开心事。",
    avatar: "https://www.yiyou.bj.cn/logo/youlogo.png",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 20,
  },
  {
    name: "Vincy云昔",
    url: "https://blog.vincy1230.net/",
    description: "太阳出来了 雾就会散的",
    avatar: "https://a.vincy1230.net/blogroll/avatar.jpg",
    type: "一些好朋友~",
    screenshot: "https://a.vincy1230.net/blogroll/siteshot600.jpg",
    recommended: false,
    sort: 21,
  },
  {
    name: "ZY知识库",
    url: "https://blog.pljzy.top/",
    description: "一个技术探索与分享的平台",
    avatar: "https://blog.pljzy.top/_astro/logo.BxIxyJV1_Z19cEQW.webp",
    type: "一些好朋友~",
    screenshot: "",
    recommended: true,
    sort: 22,
  },
  {
    name: "张恒华",
    url: "https://zhh2001.github.io",
    description: "SDN研究者",
    avatar: "https://zhh2001.github.io/avatar.jpg",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 23,
  },
  {
    name: "Elykia",
    url: "https://blog.elykia.cn/",
    description: "致以无暇之人",
    avatar: "https://bu.dusays.com/2024/10/25/671b2438203a6.gif",
    type: "一些好朋友~",
    screenshot: "https://bu.dusays.com/2024/10/25/671b50dc2dd2b.png",
    recommended: false,
    sort: 24,
  },
  {
    name: "YouYou",
    url: "https://vpnnew.net/blog/",
    description: "学无止境",
    avatar: "https://vpnnew.net/youyou.png",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 25,
  },
  {
    name: "阿叶Ayeez",
    url: "https://blog.ayeez.cn",
    description: "记录自己的学习历程，记录自己的美好生活",
    avatar: "https://qiniu.ayeez.cn/avatar.jpg",
    type: "一些好朋友~",
    screenshot: "",
    recommended: true,
    sort: 26,
  },
  {
    name: "𝟞𝟙𝟡'𝕤 𝔹𝕃𝕆𝔾",
    url: "https://66619.eu.org",
    description: "𝓙𝓾𝓼𝓽 𝓪 𝓬𝓵𝓸𝓾𝓭",
    avatar: "https://pic.seln.cn/file/ava/1767406781228_619.jpg",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 27,
  },
  {
    name: "安小歪",
    url: "https://blog.anxw.cn",
    description: "陪你成为更好的自己！",
    avatar: "https://q2.qlogo.cn/headimg_dl?dst_uin=2622979530&spec=640",
    type: "一些好朋友~",
    screenshot: "https://blog.anxw.cn/img/siteshot.webp",
    recommended: false,
    sort: 28,
  },
  {
    name: "鈴奈咲桜",
    url: "https://blog.sakura.ink",
    description: "愛することを忘れないで",
    avatar: "https://q2.qlogo.cn/headimg_dl?dst_uin=2731443459&spec=5",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 29,
  },
  {
    name: "绘星里",
    url: "https://blog.storia.ren/",
    description: "一起来绘制属于自己的星星！",
    avatar: "https://blog.storia.ren/images/icon.png",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 30,
  },
  {
    name: "安知鱼",
    url: "https://blog.anheyu.com/",
    description: "生活明朗，万物可爱",
    avatar: "https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg",
    type: "一些好朋友~",
    screenshot: "https://npm.elemecdn.com/anzhiyu-theme-static@1.1.6/img/blog.anheyu.com.jpg",
    recommended: false,
    sort: 31,
  },
  {
    name: "Lifeline",
    url: "https://lifelinest.github.io/",
    description: "经世致用 自强不息",
    avatar: "http://p2.music.126.net/x55FPD2xWTqmMIFjDKXogw==/109951163513084093.jpg?param=130y130",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 32,
  },
  {
    name: "二叉树树",
    url: "https://2x.nz/",
    description: "Protect What You Love.",
    avatar: "https://q2.qlogo.cn/headimg_dl?dst_uin=2726730791&spec=0",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 33,
  },
  {
    name: "JustPureH2O",
    url: "https://justpureh2o.cn/",
    description: "穷方圆平直之情，尽规矩准绳之用",
    avatar: "https://img.justpureh2o.cn/image/667f85b1d9c307b7e9ef9f2c.jpg",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 34,
  },
  {
    name: "CcoMm",
    url: "https://blog.ccomm.top",
    description: "你要吃C4吗？",
    avatar: "https://avatars.githubusercontent.com/u/147143261",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 35,
  },
  {
    name: "TangShiMei",
    url: "https://blog.224418.xyz/",
    description: "想和你重新认识一次，从你叫什么开始",
    avatar: "https://blog.224418.xyz/img/favicon.ico",
    type: "一些好朋友~",
    screenshot: "https://pic.seln.cn/file/siteshot/IsAl8y77.png",
    recommended: true,
    sort: 36,
  },
  {
    name: "热衷于de博客",
    url: "https://zooyoo.top/",
    description: "一个有趣的灵魂",
    avatar: "https://zooyoo.top/img/l.png",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 37,
  },
  {
    name: "min的小窝",
    url: "https://flyblog.qzz.io/",
    description: "一个热爱科技的初中生",
    avatar: "https://blog.346247.xyz/img/1.webp",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 38,
  },
  {
    name: "Windsky",
    url: "https://blog.windsky.top",
    description: "分享技术，记录生活",
    avatar: "https://api.blog.windsky.top/uploads/20260419142010_resk5udp.jpg",
    type: "一些好朋友~",
    screenshot: "https://pic.seln.cn/file/picui/yNNg5tVh.png",
    recommended: false,
    sort: 39,
  },
  {
    name: "Zenghr",
    url: "https://blog.zenghr.cn/",
    description: "平凡日子，也值得落笔珍藏",
    avatar: "https://blog.zenghr.cn/static/img/avatar.jpg",
    type: "一些好朋友~",
    screenshot: "https://media.zenghr.cn/blog-prod/screenshot-blog.webp",
    recommended: false,
    sort: 40,
  },
  {
    name: "素心",
    url: "https://haiy.space/",
    description: "我来互联网是当皇帝的",
    avatar: "https://haiy.space/uploads/images/2026/05/04ea5fddc86ae2ca.jpg",
    type: "一些好朋友~",
    screenshot: "https://pic.seln.cn/file/picui/22jfhTRv.png",
    recommended: false,
    sort: 41,
  },
  {
    name: "硬件日记",
    url: "https://blog.tyh123.top/",
    description: "记录嵌入式学习过程。",
    avatar: "https://blog.tyh123.top/img/avatar.jpg",
    type: "一些好朋友~",
    screenshot: "https://blog.tyh123.top/img/site_cover.png",
    recommended: false,
    sort: 42,
  },
  {
    name: "他说",
    url: "https://090909.top/",
    description: "梁栋烨的博客网站。",
    avatar: "https://090909.top/assets/images/logo.ico",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 43,
  },
  {
    name: "桃之夭夭",
    url: "https://taozhiyy.top",
    description: "桃之夭夭的小屋",
    avatar: "https://tzyy-1330068502.cos.ap-beijing.myqcloud.com/1.png",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 44,
  },
  {
    name: "HGL Blog 🌸",
    url: "https://hgl123.icu",
    description: "全栈开发者 · 二次元爱好者",
    avatar: "https://pic.seln.cn/file/picui/rnKy6XpK.webp",
    type: "一些好朋友~",
    screenshot: "https://i.seln.cn/file/picui/1787293001734__D88E2FD1-E8F6-452B-9F02-7CD38D340A83_.webp",
    recommended: false,
    sort: 45,
  },
  {
    name: "Hyde",
    url: "https://seasir.top/",
    description: "人心中的成见是一座大山",
    avatar: "https://seasir.top/assets/avatar.avif",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 47,
  },
  {
    name: "靈夢",
    url: "https://rain.moe",
    description: "你在那里像风一样自由，就如同奇迹一般",
    avatar: "https://img.rain.moe/static/head.webp",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 48,
  },
  {
    name: "Sigrika",
    url: "https://qwq.sigrika.cc/",
    description: "记录我的二次元之旅",
    avatar: "https://qwq.sigrika.cc/assets/images/avatar.gif",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 49,
  },
  {
    name: "酥米",
    url: "https://www.sumi233.top",
    description: "终有一日，寻梦中人",
    avatar: "https://jsd-proxy.ygxz.in/gh/huang233893/blog-image-bed@main/top/huang233893/imgs/blog/usersumi.png",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 50,
  },
  {
    name: "清羽飞扬",
    url: "https://blog.liushen.fun/",
    description: "柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜",
    avatar: "https://blog.liushen.fun/info/avatar.ico",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 51,
  },
  {
    name: "小生",
    url: "https://www.zsso.cn",
    description: "天生我材必有用，千金散尽还复来",
    avatar: "https://file.zsso.cn/userAvatar/ZSSO11781011904472445.jpg",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 52,
  },
  {
    name: "夏夜流萤",
    url: "https://blog.cuteleaf.cn",
    description: "飞萤之火自无梦的长夜亮起，绽放在终竟的明天",
    avatar: "https://weavatar.com/avatar/d252655d40d6874417a720bad0a6c5f77f8f6a1fd2f882f8f338402dc37e4190?s=640",
    type: "一些好朋友~",
    screenshot: "https://i.seln.cn/file/picui/1784535983177__1C954C1E-EDC3-46D6-8D16-450E69944838_.webp",
    recommended: false,
    sort: 53,
  },
  {
    name: "团子蛋糕",
    url: "https://blog.tsh520.cn",
    description: "如果你喜欢那么欢迎来到我的世界！",
    avatar: "https://re.tsh520.cn/zl/tx.webp",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 54,
  },
  {
    name: "云灿",
    url: "https://blog.yuncan.xyz/",
    description: "浮云一别后，流水十年间",
    avatar: "https://yuncan.xyz/images/icon/favicon.ico",
    type: "一些好朋友~",
    screenshot: "https://api.yuncan.xyz/blog/260619_193332.webp",
    recommended: false,
    sort: 55,
  },
  {
    name: "楠枝小笺",
    url: "https://www.nannax.top",
    description: "安安静静地存在，就已经很好啦",
    avatar: "https://www.nannax.top/upload/avatar.jpg",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 56,
  },
  {
    name: "兔兔の博客",
    url: "https://tutu.pink",
    description: "记录一些有趣的事情丷",
    avatar: "https://tutu.pink/images/logo.png",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 57,
  },
  {
    name: "Aimerting",
    url: "https://blog.xuioo.com/",
    description: "「纯粹祈愿皆成真」",
    avatar: "https://blog.xuioo.com/avatar.jpg",
    type: "一些好朋友~",
    screenshot: "https://blog.xuioo.com/assets/images/web-pc.webp",
    recommended: false,
    sort: 58,
  },
  {
    name: "sliorean",
    url: "https://sliorean.site",
    description: "个人技术博客，记录 AI Agent 研究与日常折腾",
    avatar: "https://sliorean.site/images/avatar.webp",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 59,
  },
  {
    name: "JerryLife",
    url: "https://www.jerrynis.com/",
    description: "Enjoy life",
    avatar: "https://img.jerry-nis.top/d8703c5c-4c4a-49cc-bd94-3363c9eda2d8.png",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 60,
  },
  {
    name: "星辰の笔记",
    url: "https://blog.strarry.top",
    description: "Code | Think | Share | Repeat",
    avatar: "https://blog.strarry.top/uploads/avatar.webp",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 61,
  },
  {
    name: "Mistlane",
    url: "https://blog.mistlane.top",
    description: "记录代码、学习与日常",
    avatar: "https://blog.mistlane.top/images/marcus.png",
    type: "一些好朋友~",
    screenshot: "https://blog.mistlane.top/images/a.jpg",
    recommended: false,
    sort: 62,
  },
  {
    name: "Bai’Blog",
    url: "https://baiblog.vip",
    description: "Actions speak louder than words",
    avatar: "https://baiblog.vip/images/5.png",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 63,
  },
  {
    name: "xiaodaidai",
    url: "https://xiaodaidai.site",
    description: "星凝眉上字，潮敛贝中音。",
    avatar: "https://xiaodaidai.site/assets/picture/%E5%A4%B4%E5%83%8F%E8%83%8C%E9%9D%A2.jpeg",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 64,
  },
  {
    name: "星空驿站",
    url: "https://baiyangmu.xyz",
    description: "一座漂浮在深空中的小小驿站",
    avatar: "https://baiyangmu.xyz/static/favicon-96x96.png",
    type: "一些好朋友~",
    screenshot: "",
    recommended: false,
    sort: 65,
  },
  {
    name: "Heithon's blog",
    url: "http://heithon",
    description: "不停的给自己加上杠杆，总有一天能撬动地球",
    avatar: "https://csjs.eu.org/img/404.jpg",
    type: "已失联",
    screenshot: "",
    recommended: false,
    sort: 65,
  },
  {
    name: "爱编程的小明",
    url: "https://kebuaaa.github.io/links/",
    description: "不要温和地走进那个良夜",
    avatar: "https://gcore.jsdelivr.net/gh/kebuAAA/Picloud@main/img/avatar.webp",
    type: "已失联",
    screenshot: "",
    recommended: false,
    sort: 66,
  },
  {
    name: "鹤归",
    url: "https://blog.tovoao.cn",
    description: "总有人间一两风 填我十万八千梦",
    avatar: "https://csjs.eu.org/img/404.jpg",
    type: "已失联",
    screenshot: "https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/anheyu.com/https://blog.tovoao.cn/",
    recommended: false,
    sort: 67,
  },
  {
    name: "洋洋のBlog",
    url: "https://blog.zoc.asia/",
    description: "Who are you？",
    avatar: "https://csjs.eu.org/img/404.jpg",
    type: "已失联",
    screenshot: "",
    recommended: false,
    sort: 68,
  },
  {
    name: "Serenity's Blog",
    url: "https://serenity.aobp.cn/",
    description: "热爱可抵岁月漫长",
    avatar: "https://csjs.eu.org/img/404.jpg",
    type: "已失联",
    screenshot: "",
    recommended: false,
    sort: 69,
  },
  {
    name: "28.7",
    url: "https://blog.kong.college/",
    description: "空山不见人，但闻人语响",
    avatar: "https://image.kong.college/i/2025/09/09/spq9n6.png",
    type: "已失联",
    screenshot: "https://image.kong.college/i/2025/09/18/seixpl.png",
    recommended: false,
    sort: 70,
  },
  {
    name: "qingshen's blog",
    url: "https://qsblog.top",
    description: "心之所向，素履以往",
    avatar: "https://img.dooki.cloud/i/2025/10/06/68e359037b0c1.webp",
    type: "已失联",
    screenshot: "",
    recommended: false,
    sort: 71,
  },
  {
    name: "LYEy_isine",
    url: "https://caiyifeng.top",
    description: "花海无一日,少年踏自来",
    avatar: "https://img.cdn1.vip/i/68bbdee513eb9_1757142757.webp",
    type: "已失联",
    screenshot: "",
    recommended: false,
    sort: 72,
  },
  {
    name: "流欺",
    url: "https://blog.lqay",
    description: "嗯对就是个博客",
    avatar: "https://tc.lqay.cn/LightPicture/2026/03/5f64e0f0f361e19c.png",
    type: "已失联",
    screenshot: "",
    recommended: false,
    sort: 73,
  },
];
