import type { APIRoute } from 'astro';

const getRobotsTxt = (sitemapURL: URL, origin: string) =>
  `# robots.txt for ${origin}
# Generated by Astro - ${new Date().toISOString().split('T')[0]}

# 允许所有爬虫访问公开内容
User-agent: *
Allow: /

# 禁止访问管理后台和API
Disallow: /admin/
Disallow: /api/

# 禁止访问私有目录和系统文件
Disallow: /.astro/
Disallow: /uploads/
Disallow: /scripts/
Disallow: /.workbuddy/
Disallow: /.backup/
Disallow: /node_modules/

# 禁止访问开发/私有页面
Disallow: /private/
Disallow: /draft/
Disallow: /test/

# 站点地图
Sitemap: ${sitemapURL.href}

# 针对 Googlebot 的优化规则
User-agent: Googlebot
Allow: /
Disallow: /admin/
Disallow: /api/
Disallow: /.astro/
Disallow: /uploads/
Disallow: /scripts/
Disallow: /.workbuddy/
Disallow: /.backup/
Crawl-delay: 1

# 针对 Bingbot 的优化规则
User-agent: Bingbot
Allow: /
Disallow: /admin/
Disallow: /api/
Disallow: /.astro/
Crawl-delay: 1

# 针对百度蜘蛛的优化规则
User-agent: Baiduspider
Allow: /
Disallow: /admin/
Disallow: /api/
Disallow: /.astro/
Crawl-delay: 1
`;

export const GET: APIRoute = ({ url }) => {
  const sitemapURL = new URL('sitemap.xml', url.origin);
  const robotsTxt = getRobotsTxt(sitemapURL, url.origin);
  
  return new Response(robotsTxt, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=86400', // 缓存 24 小时
    },
  });
};


